steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build container image'
  args: [
    'build',
    '.',
    '-t',
    'us-central1-docker.pkg.dev/mnist-cnn-447812/repository/gcp_test_app:latest',
    '-f',
    'simple_fastapi_app.dockerfile'
  ]
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push container image'
  args: [
    'push',
    'us-central1-docker.pkg.dev/mnist-cnn-447812/repository/gcp_test_app:latest'
  ]
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'Deploy to Cloud Run'
  args: [
    'run',
    'deploy',
    'simple-fastapi',
    '--image',
    'us-central1-docker.pkg.dev/mnist-cnn-447812/repository/gcp_test_app:latest',
    '--region',
    'us-central1',
    '--platform',
    'managed',
    '--allow-unauthenticated'
  ]
options:
  logging: CLOUD_LOGGING_ONLY